import { useRef, useState } from 'react'
import type { ChangeEvent, FormEvent, ReactNode, RefObject } from 'react'
import { Bot, FileText, FolderOpen, LayoutDashboard, LoaderCircle, MessageSquareText, MoreHorizontal, Plus, Send, Settings, ShieldCheck, Upload, Users } from 'lucide-react'

type View = 'overview' | 'documents' | 'chat' | 'users'
type Status = 'Ready' | 'Processing' | 'Queued'
type Doc = { id: number; name: string; owner: string; updated: string; status: Status; chunks: number | null }
const initialDocs: Doc[] = [
  { id: 1, name: 'SOP Perjalanan Dinas 2026.pdf', owner: 'Operations', updated: '18 Aug 2026, 10:42', status: 'Ready', chunks: 42 },
  { id: 2, name: 'Kebijakan Keamanan Informasi.docx', owner: 'IT Security', updated: '18 Aug 2026, 09:16', status: 'Ready', chunks: 28 },
  { id: 3, name: 'Panduan Procurement.pdf', owner: 'Finance', updated: '17 Aug 2026, 16:30', status: 'Processing', chunks: null },
]
const nav = [{ id: 'overview' as const, label: 'Overview', icon: LayoutDashboard }, { id: 'documents' as const, label: 'Documents', icon: FolderOpen }, { id: 'chat' as const, label: 'AI Chat', icon: MessageSquareText }, { id: 'users' as const, label: 'Users', icon: Users }]

export default function App() {
  const [view, setView] = useState<View>('overview'); const [docs, setDocs] = useState(initialDocs); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState(''); const uploadRef = useRef<HTMLInputElement>(null)
  const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setDocs((current) => [{ id: Date.now(), name: file.name, owner: 'You', updated: 'Just now', status: 'Queued', chunks: null }, ...current]); event.target.value = '' }
  const ask = (event: FormEvent) => { event.preventDefault(); if (!question.trim()) return; setAnswer('Mock response: the backend and AI retrieval service are not connected yet. Production answers will contain grounded claims and returned citations only.'); setQuestion('') }
  const ready = docs.filter((doc) => doc.status === 'Ready').length
  return <main className="shell"><aside><div className="brand"><Bot size={22} /> Enterprise AI</div><small>WORKSPACE</small><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'nav active' : 'nav'} onClick={() => setView(id)}><Icon size={18} /><span>{label}</span></button>)}</nav><div className="side-bottom"><button className="nav"><Settings size={18} /><span>Settings</span></button><div className="profile"><b>AR</b><span><strong>Admin</strong><small>Enterprise workspace</small></span><MoreHorizontal size={17} /></div></div></aside><section><header><span>Workspace / <strong>{nav.find((item) => item.id === view)?.label}</strong></span></header><div className="page">{view === 'overview' && <Overview ready={ready} processing={docs.length - ready} openDocs={() => setView('documents')} openChat={() => setView('chat')} />}{view === 'documents' && <Documents docs={docs} refInput={uploadRef} upload={upload} />}{view === 'chat' && <Chat question={question} setQuestion={setQuestion} answer={answer} ask={ask} />}{view === 'users' && <UsersPage />}</div></section></main>
}
function Heading({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: ReactNode }) { return <div className="heading"><div><small className="eyebrow">{eyebrow}</small><h1>{title}</h1><p>{text}</p></div>{action}</div> }
function Overview({ ready, processing, openDocs, openChat }: { ready: number; processing: number; openDocs: () => void; openChat: () => void }) { return <><Heading eyebrow="ENTERPRISE KNOWLEDGE SYSTEM" title="Knowledge workspace" text="Keep company knowledge traceable, searchable, and ready for grounded answers." action={<button className="primary" onClick={openDocs}><Upload size={17} /> Upload document</button>} /><div className="metrics"><Metric icon={FileText} label="Ready documents" value={ready} /><Metric icon={LoaderCircle} label="In processing" value={processing} /><Metric icon={MessageSquareText} label="Questions this week" value={0} /></div><div className="split"><div><h2>Document activity</h2><p>Latest processing events from your knowledge base.</p><div className="activity"><StatusBadge value="Ready" /><span>SOP Perjalanan Dinas 2026.pdf is ready for retrieval</span><time>10:42</time></div><div className="activity"><StatusBadge value="Processing" /><span>Panduan Procurement.pdf is being indexed</span><time>16:30</time></div></div><div className="evidence"><ShieldCheck size={23} /><h2>Evidence-first answers</h2><p>AI answers appear only when relevant document evidence is available.</p><button className="secondary" onClick={openChat}>Open AI Chat</button></div></div></> }
function Documents({ docs, refInput, upload }: { docs: Doc[]; refInput: RefObject<HTMLInputElement | null>; upload: (event: ChangeEvent<HTMLInputElement>) => void }) { return <><Heading eyebrow="KNOWLEDGE BASE" title="Documents" text="Upload and monitor source material used by AI Chat." action={<><button className="primary" onClick={() => refInput.current?.click()}><Upload size={17} /> Upload document</button><input className="hidden" ref={refInput} type="file" accept=".pdf,.docx" onChange={upload} /></>} /><div className="table"><table><thead><tr><th>Document</th><th>Owner</th><th>Updated</th><th>Status</th><th>Chunks</th></tr></thead><tbody>{docs.map((doc) => <tr key={doc.id}><td><span className="file"><FileText size={17} />{doc.name}</span></td><td>{doc.owner}</td><td>{doc.updated}</td><td><StatusBadge value={doc.status} /></td><td>{doc.chunks ?? '...'}</td></tr>)}</tbody></table></div></> }
function Chat({ question, setQuestion, answer, ask }: { question: string; setQuestion: (value: string) => void; answer: string; ask: (event: FormEvent) => void }) { return <div className="chat"><Heading eyebrow="RETRIEVAL-AUGMENTED CHAT" title="Ask your knowledge base" text="Answers will include sources retrieved by the AI service." /><div className="thread">{answer ? <div className="answer"><strong><Bot size={17} /> Enterprise AI</strong><p>{answer}</p><span><FileText size={16} /> Citations will appear after integration.</span></div> : <div className="empty"><Bot size={34} /><h2>What do you need to know?</h2><p>Ask a question about an approved document.</p></div>}</div><form onSubmit={ask}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask a question about your documents" /><button className="send" title="Send"><Send size={18} /></button></form></div> }
function UsersPage() { return <><Heading eyebrow="ACCESS MANAGEMENT" title="Users" text="This view will connect to the backend user and permission API." action={<button className="primary"><Plus size={17} /> Add user</button>} /><div className="empty"><Users size={32} /><h2>User API not connected</h2><p>The frontend is ready for the backend user contract.</p></div></> }
function Metric({ icon: Icon, label, value }: { icon: typeof FileText; label: string; value: number }) { return <div className="metric"><Icon size={20} /><span>{label}<strong>{value}</strong></span></div> } function StatusBadge({ value }: { value: Status }) { return <span className={`status ${value.toLowerCase()}`}>{value === 'Processing' && <LoaderCircle size={13} />}{value}</span> }
